CURRENT_SHELL="bash"
SHELL_FILES="$(dirname $(readlink $BASH_SOURCE))"
DOT_FILES="$(dirname $(dirname $SHELL_FILES))"

source $DOT_FILES/shells/bootstrap.sh

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
